/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    '../.tmp/templates.html',
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#001320",
        "primary-container": "#0b293a",
        "primary-fixed": "#cae6fd",
        "primary-fixed-dim": "#aecae0",
        "on-primary": "#ffffff",
        "on-primary-container": "#7691a5",
        "on-primary-fixed": "#001e2e",
        "surface": "#fff9ef",
        "surface-bright": "#fff9ef",
        "surface-dim": "#dfd9d0",
        "surface-tint": "#476175",
        "surface-variant": "#e7e2d8",
        "surface-container": "#f3ede3",
        "surface-container-low": "#f9f3e9",
        "surface-container-high": "#ede7de",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e7e2d8",
        "on-surface": "#1d1b16",
        "on-surface-variant": "#42474c",
        "secondary": "#6d5c41",
        "secondary-container": "#f4dcba",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#726045",
        "tertiary": "#111111",
        "tertiary-container": "#262626",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#8e8d8d",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "outline": "#73787c",
        "outline-variant": "#c2c7cc",
        "inverse-primary": "#aecae0",
        "inverse-surface": "#32302a",
        "inverse-on-surface": "#f6f0e6",
      },
      fontFamily: {
        sans:    ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body:    ['Inter', 'sans-serif'],
        label:   ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
